//20170812 Umi Added
var app = new Vue({
    el:'#root',
    data:{
      test:[
        {
          title:'T211231Title',
          subtitle:'subtitle',
          links:'http://www.baidu.com',
          group:'test'
        },
        {
          title:'T211321231231231Title',
          subtitle:'subtitle',
          links:'http://www.baidu.com',
          group:'test'
        }
      ],
      archfiles:[
        {
          title:'Sample1',
          subtitle:'subtitle',
          links:'http://www.baidu.com',
          group:'classic'
        },
        {
          title:'Sample2',
          subtitle:'subtitle',
          links:'http://www.baidu.com',
          group:'classic'
        },
        {
          title:'Sample9',
          subtitle:'subtitle',
          links:'http://www.baidu.com',
          group:'digital'
        },
        {
          title:'Sample5',
          subtitle:'subtitle',
          links:'http://www.baidu.com',
          group:'silver'
        },
        {
          title:'Sample55',
          subtitle:'subtitle',
          links:'http://www.baidu.com',
          group:'exhibition'
        },
        {
          title:'Sample333',
          subtitle:'subtitle',
          links:'http://www.baidu.com',
          group:'digital'
        }
      ],
      checkflag:'classic'
    },
    methods:{
      navito:function(e){
        //console.log(e.currentTarget);
        //console.log(e.currentTarget.getAttribute("href"));
        location.href = e.currentTarget.getAttribute("href");
      },
      changecheckflag:function(str){
                this.checkflag=str;
            }
    }
  })